### ISSUE TITLE
Regra de validação não funciona na Model

### ISSUE THREAD

**Issue by c0destep** [aplus-framework/validation#1]
A regra "optional" parece não funcionar quando validado através de uma classe Model, fora isso funciona corretamente.

**Comment by natanfelles** [comment]
Olá, @c0destep !
Acabei de testar e está funcionando corretamente.

Por favor, coloque o código de exemplo que parece não funcionar para que possamos analisar.

**Comment by natanfelles** [comment]
Conforme o [guia do usuário](https://docs.aplus-framework.com/guides/libraries/validation/index.html#optional):

> The field is optional. If not present, validation passes.

Se o campo estiver presente, as outras regras serão validadas.

Para "estar presente" significa que o campo possui qualquer valor exceto `null`.
Se ele não estiver definido ou for `null`, as outras regras não serão validadas e a validação passa.

**Comment by c0destep** [comment]
> Olá, @c0destep ! Acabei de testar e está funcionando corretamente.
> 
> Por favor, coloque o código de exemplo que parece não funcionar para que possamos analisar.

Regra da Model
```php
protected array $validationRules = [
    'name' => 'optional|regex:/^((\b[A-zÀ-ú]{3\,50}\b)\s*){2\,}$/',
    'username' => 'required|regex:/^(?!.*\.\.)(?!.*\.$)[^\W][\w.]{2\,24}$/'
];
```

Chamando função create
```php
$userMetaModel = new UsersMetaModel();
$userMeta = $userMetaModel->create([
    'name' => $this->request->getPost('name'),
    'username' => $this->request->getPost('username')
]);
```

Mesmo quando `null` ele verifica as demais regras.

**Comment by natanfelles** [comment]
@c0destep , desculpe por me precipitar nos  comentários anteriores pois expliquei o comportamente da regra `optional` de maneira equivocada.

Acontece que para "estar presente" significa que o campo está definido, independente do valor.

Então, quando o campo é `null` também é considerado presente (definido):

No seu exemplo, você pode chamar o método create com todos os campos recebidos:

```php
$userMeta = $userMetaModel->create($this->request->getPost());
```

Pode ficar tranquilo pois os campos serão filtrados na model de acordo com os `$allowedFields`.

Então, um campo com `null` também é considerado presente. Isso acontece porque pode ser desejado, por exemplo, setar um campo no banco de dados com o valor `NULL` através de uma API com JSON.

Penso em atualizar a descrição da regra:

```diff
- The field is optional. If not present, validation passes.
+ The field is optional. If undefined, validation passes.
```

Você teria alguma sugestão de como fazer isso ser mais compreensível?

**Comment by c0destep** [comment]
Desta nova forma já está de melhor entendimento.
